### PR TITLE
unit test for non multipart interception

### PR DESCRIPTION
**Pull request by atzoum**
changed the readme a bit as well to reflect the new reality :)

### CODE REVIEW

**Comment by atzoum** [comment]
https://github.com/ifad/clammit/pull/4 contains some unit tests

**Comment by vjt** [comment]
Thanks for this, @atzoum! What about defining `ClamInterceptor` as an interface, and then, via embedding, defining a `MockInterceptor` type in the unit test, that overrides the `scan()` function?

This would avoid the `clamavScanner` global variable, [leaked to main.go](https://github.com/ifad/clammit/pull/4/files#diff-106b49222ab1f7af3b90611abe013d80R173).

Thoughts?

Thanks!

**Comment by atzoum** [comment]
Can you please elaborate a bit? 
`Scan` is called internally by `ClamInterceptor#respondOnVirus`. A `ClamInterceptor` interface would only make sense to have a `Handle` method, which happens to be the one we need to test. How would embedding help on this case?
Would it make more sense to define a `Scanner` interface along with its default implementation on a separate file? This is a classic composition design. `ClamInterceptor` just needs a `Scanner` to delegate file scanning to and `main` is responsible to create the interceptor with the appropriate scanner.

PS. I am fairly new to golang, indeed, I just learnt about the existence of embedding from you, so please bear with me :)

**Comment by atzoum** [comment]
please see the [second commit](https://github.com/ifad/clammit/pull/4/commits/2136dcdc7e46d0a052d23c2c1eea93ad8977f127) as an example

**Comment by vjt** [comment]
Excellent, @atzoum! It makes a lot of sense, as it opens the door to multiple scanner support :smiley:. I would move also the scanner initialisation code in the ScanInterceptor, decoupling the clamav-specific NewClamd from main.go.

What do you think?

Thanks!

**Comment by atzoum** [comment]
please see https://github.com/ifad/clammit/pull/4/commits/a78c2513c5c5037d84aefaf212abe61809114ca6. I believe that this has grown beyond initial expectations so I guess we need to refrain from any further refactoring ;)

**Comment by vjt** [comment]
Neat! I have some ideas on how to DRY this a bit, I will play with it tonight. Agreed the refactoring should then stop :-D

Later

**Comment by atzoum** [comment]
hi @vjt, any update on this?

**Comment by vjt** [comment]
Hey @atzoum - it's been a /long/ week, but with the weekend ahead I will have time to dedicate to clammit.

Sorry for the wait :-)

**Comment by atzoum** [comment]
hi @vjt, did you have any time to look into this?

**Comment by vjt** [comment]
Hi @atzoum, yes, I had fun during the afternoon :-) I'm now finishing writing a test for multipart uploads and I'll push soon!

**Comment by vjt** [comment]
Opened #6 that includes this.

**Pull request closed without merging**
