### PR TITLE
Remove vendored code

### LINKED ISSUE #1: Switch to maintained fork of go-clamd
As reported by @jblackman:

> The dutchcoders master branch of go-clamd no longer seems to be maintained. There is a [more recent fork](https://github.com/Freeaqingme/go-clamd) that contains a couple of fixes that might be better for you.

### PR DESCRIPTION
**Pull request by vjt**
This fixes #1 by moving to from @dutchcoders's go-clamd to @Freeaqingme's fork, that removes annoying logging and adds more structured responses.

### CODE REVIEW

**Comment by vjt** [comment]
@atzoum wdyt? :-)

**Comment by vjt** [comment]
@jblackman your feedback is also very welcome

**Comment by jblackman** [comment]
Looks good. The @dutchcoders guys move pretty slowly, but keep an eye out for them merging in the changes from the @Freeaqingme fork, assuming he ever bothers with a merge request.

**Comment by vjt** [comment]
Thanks both! Merging and cutting a v0.6.0 release.

**Pull request merged**
